[2024-03-23T23:22:24.171+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:22:24.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:22:24.173+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:22:24.172+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:22:24.178+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:22:24.177+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:22:24.178+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:22:24.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.027 seconds
[2024-03-23T23:22:54.606+0000] {processor.py:161} INFO - Started process (PID=404) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:22:54.608+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:22:54.609+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:22:54.609+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:22:54.616+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:22:54.614+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:22:54.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:22:54.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.034 seconds
[2024-03-23T23:23:45.329+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:23:45.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:23:45.330+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:23:45.330+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:23:45.334+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:23:45.333+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:23:45.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:23:45.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.019 seconds
[2024-03-23T23:24:15.662+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:24:15.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:24:15.664+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:24:15.664+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:24:15.671+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:24:15.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:24:15.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:24:15.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.032 seconds
[2024-03-23T23:24:46.052+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:24:46.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:24:46.055+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:24:46.055+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:24:46.061+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:24:46.060+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:24:46.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:24:46.080+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.033 seconds
[2024-03-23T23:25:16.514+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:25:16.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:25:16.517+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:25:16.517+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:25:16.524+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:25:16.523+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:25:16.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:25:16.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.034 seconds
[2024-03-23T23:25:46.883+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:25:46.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:25:46.885+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:25:46.885+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:25:46.892+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:25:46.891+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:25:46.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:25:46.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.034 seconds
[2024-03-23T23:26:17.298+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:26:17.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:26:17.301+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:26:17.301+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:26:17.307+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:26:17.306+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:26:17.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:26:17.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.033 seconds
[2024-03-23T23:26:47.686+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:26:47.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:26:47.689+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:26:47.688+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:26:47.695+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:26:47.694+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:26:47.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:26:47.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.032 seconds
[2024-03-23T23:27:18.055+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:27:18.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:27:18.057+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:27:18.057+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:27:18.062+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:27:18.061+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:27:18.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:27:18.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.028 seconds
[2024-03-23T23:27:48.444+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:27:48.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:27:48.446+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:27:48.446+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:27:48.456+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:27:48.455+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:27:48.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:27:48.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.028 seconds
[2024-03-23T23:28:18.763+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:28:18.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:28:18.764+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:28:18.764+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:28:18.768+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:28:18.767+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:28:18.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:28:18.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.021 seconds
[2024-03-23T23:28:42.078+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:28:42.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:28:42.080+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:28:42.080+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:28:42.086+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:28:42.085+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:28:42.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:28:42.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.023 seconds
[2024-03-23T23:28:56.331+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:28:56.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:28:56.334+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:28:56.334+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:28:56.343+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:28:56.342+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:28:56.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:28:56.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.036 seconds
[2024-03-23T23:29:26.741+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:29:26.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:29:26.743+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:29:26.743+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:29:26.749+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:29:26.748+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:29:26.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:29:26.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.026 seconds
[2024-03-23T23:29:57.078+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:29:57.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:29:57.081+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:29:57.080+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:29:57.088+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:29:57.087+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:29:57.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:29:57.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.037 seconds
[2024-03-23T23:30:13.543+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:30:13.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:30:13.545+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:30:13.545+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:30:13.548+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:30:13.548+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:30:13.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:30:13.559+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.018 seconds
[2024-03-23T23:30:43.875+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:30:43.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:30:43.877+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:30:43.877+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:30:43.883+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:30:43.882+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:30:43.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:30:43.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.032 seconds
[2024-03-23T23:31:14.237+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:31:14.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:31:14.239+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:31:14.239+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:31:14.244+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:31:14.243+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:31:14.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:31:14.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.028 seconds
[2024-03-23T23:31:44.560+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:31:44.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:31:44.561+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:31:44.561+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:31:44.566+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:31:44.565+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 1, in <module>
    from airflow import DAG, PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-03-23T23:31:44.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:31:44.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.024 seconds
[2024-03-23T23:32:00.760+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:32:00.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:32:00.763+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:32:00.762+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:32:00.777+0000] {processor.py:840} INFO - DAG(s) 'our_dag_with_python_operator_v01' retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:32:00.838+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:32:00.838+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:our_dag_with_python_operator_v01
[2024-03-23T23:32:00.844+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:32:00.843+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:our_dag_with_python_operator_v01
[2024-03-23T23:32:00.848+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:32:00.848+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:our_dag_with_python_operator_v01
[2024-03-23T23:32:00.848+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:32:00.848+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-23T23:32:00.854+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:32:00.853+0000] {dag.py:3069} INFO - Creating ORM DAG for our_dag_with_python_operator_v01
[2024-03-23T23:32:00.859+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:32:00.859+0000] {dag.py:3834} INFO - Setting next_dagrun for our_dag_with_python_operator_v01 to 2024-03-24 00:00:00+00:00, run_after=2024-03-25 00:00:00+00:00
[2024-03-23T23:32:00.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.111 seconds
[2024-03-23T23:32:31.172+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:32:31.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/create_dag_with_python_operator.py for tasks to queue
[2024-03-23T23:32:31.174+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:32:31.174+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:32:31.189+0000] {processor.py:840} INFO - DAG(s) 'our_dag_with_python_operator_v01' retrieved from /opt/airflow/dags/create_dag_with_python_operator.py
[2024-03-23T23:32:31.213+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:32:31.213+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-23T23:32:31.232+0000] {logging_mixin.py:188} INFO - [2024-03-23T23:32:31.232+0000] {dag.py:3834} INFO - Setting next_dagrun for our_dag_with_python_operator_v01 to 2024-03-24 00:00:00+00:00, run_after=2024-03-25 00:00:00+00:00
[2024-03-23T23:32:31.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/create_dag_with_python_operator.py took 0.079 seconds
