[2024-03-24T17:45:24.785+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: our_dag_with_python_operator_v04.greet manual__2024-03-24T17:40:21.563761+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
